### ISSUE TITLE
ReaderClosedException

### ISSUE THREAD

**Issue by eaba** [Horusiath/Akka.Persistence.Pulsar#2]
```
[ERROR][1/11/2020 4:27:10 PM][Thread 0004][akka://SampleSystem/user/SampleActor] Persistence failure when replaying events for persistenceId [sampleActor]. Last known sequence number [0]
Cause: DotPulsar.Exceptions.ReaderClosedException: Reader has closed
   at DotPulsar.Internal.Reader.<>c.<HasClosed>b__19_0()
   at DotPulsar.Internal.Reader.OnException(Exception exception, CancellationToken cancellationToken)
   at DotPulsar.Internal.Reader.Messages(CancellationToken cancellationToken)+MoveNext()
   at DotPulsar.Internal.Reader.Messages(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.WhereEnumerableAsyncIterator`1.MoveNextCore() in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\Where.cs:line 197
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\AsyncIterator.cs:line 70
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\AsyncIterator.cs:line 75
   at System.Linq.OrderedAsyncEnumerable`1.TryGetFirstAsync(CancellationToken cancellationToken) in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\OrderedAsyncEnumerable.cs:line 269
   at System.Linq.OrderedAsyncEnumerable`1.TryGetFirstAsync(CancellationToken cancellationToken) in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\OrderedAsyncEnumerable.cs:line 290
   at System.Linq.AsyncEnumerable.<FirstOrDefaultAsync>g__Core|287_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\FirstOrDefault.cs:line 24
   at Akka.Persistence.Pulsar.Snapshot.PulsarSnapshotStore.LoadAsync(String persistenceId, SnapshotSelectionCriteria criteria) in C:\Users\Technical\source\repos\Akka.Persistence.Pulsar\Akka.Persistence.Pulsar\Snapshot\PulsarSnapshotStore.cs:line 85
   at Akka.Util.Internal.AtomicState.CallThrough[T](Func`1 task)
   at Akka.Util.Internal.AtomicState.CallThrough[T](Func`1 task)
```

**Comment by eaba** [comment]
```
[ERROR][1/11/2020 4:47:46 PM][Thread 0004][akka://SampleSystem/user/SampleActor] Persistence failure when replaying events for persistenceId [sampleActor]. Last known sequence number [0]
Cause: Akka.Persistence.RecoveryTimedOutException: Recovery timed out, didn't get snapshot within 30s.
```
